session_root:
image_list_file_path:
output_dir:

mdet_config:
  model_path: "./models/md_v4.1.0.pb"
  output_absolute_path: False
  threshold: 0.95
  verbose: True
  recursive: True

mdet_crop_config:
  threshold: 0.95

clip_config:
  start_frame: 0
  end_frame:
  step: 30
  ext: jpg
  remove_banner: True
